# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::TradeExecutionMutationInput`.
# Please instead update this file by running `bin/tapioca dsl Types::TradeExecutionMutationInput`.


class Types::TradeExecutionMutationInput
  sig { returns(::String) }
  def action; end

  sig { returns(T.nilable(::String)) }
  def preferred_exchange; end

  sig { returns(T.nilable(::Float)) }
  def price; end

  sig { returns(::Float) }
  def quantity; end

  sig { returns(::String) }
  def symbol; end
end
