# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Bundler::ConnectionPool::ForkTracker; end
module Bundler::FetchMetadata; end
module Bundler::MatchMetadata; end
module Sidekiq::Process; end
module Sidekiq::SortedEntry; end
